version: '3.8'

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: carbon_tracker
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./carbon-tracker-backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      APP_ENV: local
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: carbon_tracker
      DB_USERNAME: root
      DB_PASSWORD: root

  ml-service:
    build: ./ml-service
    restart: always
    ports:
      - "8001:8001"

  frontend:
    build: ./carbon-tracker-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db_data: