<?php

namespace App\Services;

class ChatbotService
{
    protected array $rules = [
        // [keywords to look for, response]
        ['keywords' => ['hello', 'hi', 'hey'], 'response' => "Hello! I'm your Carbon Tracker assistant. Ask me about electricity, transport, plastic, your eco score, or how to reduce your footprint."],
        ['keywords' => ['eco score', 'points', 'score'], 'response' => "Your eco score goes up every time you log an activity — the lower the emissions, the more points you earn. Check your Dashboard to see your current score."],
        ['keywords' => ['leaderboard', 'rank', 'ranking'], 'response' => "The leaderboard shows the top 20 users by eco score. You can check your own rank even if you're outside the top 20."],
        ['keywords' => ['badge', 'badges', 'achievement'], 'response' => "Badges are earned automatically — for example, reaching eco score milestones or logging activities several days in a row. Check the Badges section to see what you've earned."],
        ['keywords' => ['electricity', 'power', 'energy', 'bill'], 'response' => "Electricity emissions come from your monthly bill in Riel, converted to kWh using the EDC rate, then multiplied by Cambodia's grid emission factor. Try lowering AC usage or unplugging idle devices to cut this down."],
        ['keywords' => ['transport', 'car', 'bus', 'motorcycle', 'drive', 'commute'], 'response' => "Transport emissions depend on your mode of travel and distance. Walking and cycling produce zero emissions — even switching a few car trips to a bus can noticeably lower your footprint."],
        ['keywords' => ['plastic', 'bag', 'bottle', 'straw'], 'response' => "Plastic emissions are based on the number of single-use items you use, each carrying a lifecycle CO2 cost. Reusable bags and bottles are the easiest way to bring this down."],
        ['keywords' => ['predict', 'prediction', 'forecast', 'future'], 'response' => "Our ML model predicts your expected daily emissions based on your recent electricity, transport, and plastic usage. Check the Dashboard's prediction feature to see it in action."],
        ['keywords' => ['reduce', 'lower', 'improve', 'help', 'tip', 'advice'], 'response' => "The single biggest thing you can do is look at your Recommendations page — it tells you which category (electricity, transport, or plastic) is contributing the most to your footprint, and gives targeted tips for that specific area."],
        ['keywords' => ['what is carbon footprint', 'carbon footprint', 'co2', 'emission'], 'response' => "A carbon footprint is the total amount of greenhouse gases (measured as CO2-equivalent) generated by your daily activities — electricity use, transportation, and consumption habits like plastic use."],
        ['keywords' => ['thank', 'thanks'], 'response' => "You're welcome! Every small change adds up — keep logging your activities."],
        ['keywords' => ['bye', 'goodbye'], 'response' => "Goodbye! Come back anytime to check your progress."],
    ];

    protected string $fallback = "I'm not sure about that one yet. Try asking about electricity, transport, plastic, your eco score, badges, the leaderboard, or how to reduce your carbon footprint.";

    public function respond(string $message): string
    {
        $message = strtolower(trim($message));

        foreach ($this->rules as $rule) {
            foreach ($rule['keywords'] as $keyword) {
                if (str_contains($message, $keyword)) {
                    return $rule['response'];
                }
            }
        }

        return $this->fallback;
    }
}